navigation = [
    {'id': 'aboutMe',
     'href': '/',
     'text': 'About Me'},
    {'id': 'resume',
     'href': '../static/documents/Resume.pdf',
     'text': 'Resume'},
    {'id': 'aboutSite',
     'href': '/aboutsite',
     'text': 'About This Site'},
    {'id': 'exper',
     'href': '/experience',
     'text': 'Experience'},
    {'id': 'skills',
     'href': '/skills',
     'text': 'My Skills'},
    {'id': 'writing',
     'href': '/writing',
     'text': 'Writing Portfolio'},
    {'id': 'music',
     'href': '/music',
     'text': 'Music'},
    # {'id': 'contact',
    #  'href': '/contact',
    #  'text': 'Contact Me'},

]
subheading = [
    {'href': 'http://github.com/nichow',
     'id': 'git',},
    {'href': 'http://linkedin.com/in/nicolas-garcia-4b0541140',
     'id': 'linked',},
    {'href': 'http://facebook.com/nichoww',
     'id': 'facebook',},
    {'href': 'http://twitter.com/nich0w',
     'id': 'twitter',},
    {'href': 'http://instagram.com/nichowisdead',
     'id': 'insta',},
]
stories = [
    {'href': '../static/documents/Periphery.pdf',
     'text': 'Periphery'},
#    {'href': '../static/documents/ComingHome.pdf',
#     'text': 'Coming Home'},
#    {'href': '../static/documents/musings.pdf',
#     'text': 'The Musings of an Anxiety Ridden Mind High on Marijuana'},
    {'href': '../static/documents/delirun.pdf',
     'text': 'Deli Run'},
    {'href': '../static/documents/chess.pdf',
     'text': 'Chess'},
]
essays = [
    {'href': '../static/documents/catan.pdf',
     'text': 'Settlers of Catan Analysis'},
    {'href': '../static/documents/doom.pdf',
     'text': 'DOOM (2016) Analysis'},
    {'href': '../static/documents/Dark%20Souls.pdf',
     'text': 'Dark Souls Gameplay Analysis'},
    {'href': '../static/documents/Dark%20Souls%202.pdf',
     'text': 'Dark Souls; or, Throwing Stones in a Glass House'},
    {'href': 'https://www.youtube.com/watch?v=BRq8OLfRu_M',
     'text': 'Video Version of the Above Essay'},
    {'href': '../static/documents/Nier.pdf',
     'text': 'Nier Automata and Nietzsche'}
]
